config/routes.rb
Rails.application.routes.draw do


  mount Payola::Engine => '/payola', as: :payola
  localized do
    #devise
    devise_for :users, :controllers => { :registrations => 'registrations' }
    devise_for :admin, :controllers => { :registrations => 'adminregistrations' }
    root 'shop/catalogs#index'

    #shop
    namespace :shop do
      root 'catalogs#index'

      get 'contact',to: 'static#contact'
      get 'testimonials',to: 'static#testimonials',as: 'testimonials'
      get 'about_us',to: 'static#aboutus',as: 'aboutus'

      resources :catalogs, only: [:index,:show]
      resources :categories, only: [:index,:show]
      resources :products, only: [:index,:show]
      resources :offers, only: [:index,:show]
      resources :brands, only: [:index,:show]

    end

    #panel
    namespace :panel do
      root 'static#home'
      get 'sell',to: 'static#sell',as: 'sell'
      get 'buy',to: 'static#buy',as: 'buy'

      resources :profiles, only: [:index,:show]
      resources :orders, only: [:index,:show]
      resources :invoices, only: [:index,:show]
      resources :carts, only: [:index,:show]

      resources :brands
      resources :modells, :path => 'models'
      resources :offers

    end

    #admin
    namespace :admin do
      root 'static#home'

      resources :categorymodels
      resources :modells, :path => 'models'
      resources :activities
      resources :profiles
      resources :brands
      resources :apps, :path => 'app'
      resources :categories
      resources :offers
      resources :incoterms
      resources :conditions


    end

  end


  #TO REVIEW or delete...
  scope '(:locale)', locale: /en|fr|es|de/ do

    resources :users, only: [:index]

    resources :conversations, only: [:index, :show, :destroy] do
      member do
        post :reply
        post :restore
        post :mark_as_read
      end
      collection do
        delete :empty_trash
      end
    end
    resources :messages, only: [:new, :create]

    #get 'shop/index'
    #get 'shop/category/:id', to: 'shop#category', as: 'shop_category'


  end

  namespace :api ,constraints: { format: 'json' } do
    namespace :v1 do
      resources :categories
    end
  end
end


# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/controllers/admin/modells_controller.rb
class Admin::ModellsController < AdminController
  before_action :set_modell, only: [:show, :edit, :update, :destroy]

  # GET /modells
  # GET /modells.json
  def index
    if params[:tag]
      @modells = Modell.tagged_with(params[:tag])
    else
      @modells = Modell.all
    end
  end

  # GET /modells/1
  # GET /modells/1.json
  def show
  end

  # GET /modells/new
  def new
    @chosen_category = Category.find_by(id: params[:to].to_i) if params[:to]
    @modell = Modell.new
  end

  # GET /modells/1/edit
  def edit
  end

  def tag_cloud
    @tags = Modell.tag_counts_on(:tags)
  end

  # POST /modells
  # POST /modells.json
  def create
    @modell = Modell.new(modell_params)

    respond_to do |format|
      if @modell.save
        @categories = Category.where(id: params['categories'])
        @categories.each do |cat|
          @modell.categorymodels.create(show: cat)
        end
        format.html { redirect_to admin_modell_path(@modell), notice: 'Modell was successfully created.' }
        format.json { render :show, status: :created, location: @modell }
      else
        format.html { render :new }
        format.json { render json: @modell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /modells/1
  # PATCH/PUT /modells/1.json
  def update
    respond_to do |format|
      #TODO Improve method
      @modell.categorymodels.delete_all
      @categories = Category.where(id: params['categories'])
      @categories.each do |cat|
        @modell.categorymodels.create(show: cat)
      end
      #@modell.categorymodels.create(@categories)
      if @modell.update(modell_params)
        format.html { redirect_to admin_modell_path(@modell), notice: 'Modell was successfully updated.' }
        format.json { render :show, status: :ok, location: @modell }
      else
        format.html { render :edit }
        format.json { render json: @modell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /modells/1
  # DELETE /modells/1.json
  def destroy
    @modell.destroy
    respond_to do |format|
      format.html { redirect_to admin_modells_url, notice: 'Modell was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_modell
    @modell = Modell.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def modell_params
    params.require(:modell).permit(:name, :year, {factorypics: []},:tag_list,:enabled, :brand_id,:country_code)
  end
end

app/controllers/api/v1/modells_controller.rb
class Api::V1::CategoriesController < ApplicationController
  #respond_to :json
  before_action :set_modell, only: [:show, :edit, :update, :destroy]
  #skip_before_action :authenticate_user!, only: [:index,:show]

  # GET /modells
  def index
    @modell = Modell.all
    render json: @modell
  end


  # GET /modells/1
  def show
    render json: @modell
  end

  # POST /modells
  def create
    @modell = Modell.new(modell_params)
   if @modell.save
      render json: :created, location: @modell
    else
      render json: @modell.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /modells/1
  def update
      if @modell.update(modell_params)
        render json: :ok, location: @modell
      else
        render json: @modell.errors, status: :unprocessable_entity
      end
    end
  end

  # DELETE /modells/1
  def destroy
    @modell.destroy
    render json: :no_content
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_modell
    @modell = Modell.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def modell_params
    params.require(:modell).permit(:name, :year, {factorypics: []}, :enabled, :brand_id)
  end

app/controllers/panel/brands_controller.rb
class Panel::BrandsController < PanelController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    if params[:tag]
      @brands = Brand.tagged_with(params[:tag])
    else
      @brands = Brand.all
    end
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        #track_activity @brand
        format.html { redirect_to panel_brand_path(@brand), notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        #track_activity @brand
        format.html { redirect_to panel_brand_path(@brand), notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    #track_activity @brand
    respond_to do |format|
      format.html { redirect_to panel_brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_brand
    @brand = Brand.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def brand_params
    params.require(:brand).permit(:name, :sdescription, :description,:tag_list, :logo, :metatitle, :enable)
  end
end

app/controllers/panel/carts_controller.rb
class Panel::CartsController < PanelController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]
  #skip_before_action :authenticate_user!, only: [:index,:show],raise: false


  # GET /brands/1
  # GET /brands/1.json
  def show
    #@products=@brand.modells
  end
  def index

  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      #@brand = Brand.friendly.find(params[:id])
    end

end

app/controllers/panel/invoices_controller.rb
class Panel::InvoicesController < PanelController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]
  #skip_before_action :authenticate_user!, only: [:index,:show],raise: false


  # GET /brands/1
  # GET /brands/1.json
  def show
    #@products=@brand.modells
  end
  def index
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      #@brand = Brand.friendly.find(params[:id])
    end

end

app/controllers/panel/modells_controller.rb
class Panel::ModellsController < PanelController
  before_action :set_modell, only: [:show, :edit, :update, :destroy]

  # GET /modells
  # GET /modells.json
  def index
    if params[:tag]
      @modells = Modell.tagged_with(params[:tag])
    else
      @modells = Modell.all
    end
  end

  # GET /modells/1
  # GET /modells/1.json
  def show
  end

  # GET /modells/new
  def new
    @chosen_category = Category.find_by(id: params[:to].to_i) if params[:to]
    @modell = Modell.new
  end

  # GET /modells/1/edit
  def edit
  end

  def tag_cloud
    @tags = Modell.tag_counts_on(:tags)
  end

  # POST /modells
  # POST /modells.json
  def create
    @modell = Modell.new(modell_params)

    respond_to do |format|
      if @modell.save
        @categories = Category.where(id: params['categories'])
        @categories.each do |cat|
          @modell.categorymodels.create(show: cat)
        end
        format.html { redirect_to panel_modell_path(@modell), notice: 'Modell was successfully created.' }
        format.json { render :show, status: :created, location: @modell }
      else
        format.html { render :new }
        format.json { render json: @modell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /modells/1
  # PATCH/PUT /modells/1.json
  def update
    respond_to do |format|
      #TODO Improve method
      @modell.categorymodels.delete_all
      @categories = Category.where(id: params['categories'])
      @categories.each do |cat|
        @modell.categorymodels.create(show: cat)
      end
      #@modell.categorymodels.create(@categories)
      if @modell.update(modell_params)
        format.html { redirect_to panel_modell_path(@modell), notice: 'Modell was successfully updated.' }
        format.json { render :show, status: :ok, location: @modell }
      else
        format.html { render :edit }
        format.json { render json: @modell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /modells/1
  # DELETE /modells/1.json
  def destroy
    @modell.destroy
    respond_to do |format|
      format.html { redirect_to panel_modells_url, notice: 'Modell was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_modell
    @modell = Modell.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def modell_params
    params.require(:modell).permit(:name, :year, {factorypics: []},:tag_list,:enabled, :brand_id,:country_code)
  end
end

app/controllers/panel/offers_controller.rb
class Panel::OffersController < PanelController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    if params[:tag]
      @offers = Offer.tagged_with(params[:tag])
    else
      @offers = Offer.all
    end
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to panel_offer_path(@offer), notice: 'Offer was successfully created.' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to panel_offer_path(@offer), notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to panel_offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_offer
    @offer = Offer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def offer_params
    params.require(:offer).permit(:serialnumber, :machinenumber,:tag_list, :agedate, :condition_id, :incoterm_id, {images: []}, :description, :avability, :price_cents, :modell_id, :enabled)
  end
end

app/controllers/panel/orders_controller.rb
class Panel::OrdersController < PanelController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  #skip_before_action :authenticate_user!, only: [:index,:show],raise: false


  # GET /brands/1
  # GET /brands/1.json
  def show
    #@products=@brand.modells
  end
  def index

  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      #@brand = Brand.friendly.find(params[:id])
    end

end

app/controllers/panel/profiles_controller.rb
class Panel::ProfilesController < PanelController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to panel_profile_path(@profile), notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to panel_profile_path(@profile), notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to panel_profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:firstname, :lastname, :location, :status, :picture)
    end
end

app/controllers/panel/static_controller.rb
class  Panel::StaticController < PanelController
 #skip_before_action :authenticate_user!
  def home

  end

  def contact
  end
  def testimonials

  end
  def aboutus

  end
  def buy

  end
  def sell

  end
end

app/controllers/panel_controller.rb
class PanelController < ApplicationController
  before_action :authenticate_user!
  #protect_from_forgery with: :exception
end

app/helpers/modells_helper.rb
module ModellsHelper
  include ActsAsTaggableOn::TagsHelper

  def category_options(chosen_category = nil)
    s = ''
    Category.all.each do |cat|
      s << "<option value='#{cat.id}' data-img-src='' #{'selected' if cat == chosen_category}>#{cat.name}</option>"
    end
    s.html_safe
  end

end

app/views/panel/modells/_form.html.haml
.row
  = simple_form_for [:panel, @modell],:html => { :class => 'form-group' }  do |f|
    .col-sm-12

      = f.input :name
      = f.error_span :name
      = f.input :year
      = f.error_span :year
      -#= f.input :factorypics
      -#= f.error_span :factorypics
      = f.input :enabled
      = f.error_span :enabled
      = f.input :brand_id
      = f.error_span :brand_id

      = f.input :country_code
      = f.error_span :country_code
    .col-sm-6
      = f.button :submit, :class => 'btn-primary'
    .col-sm-6
      = link_to t('.cancel', :default => t("helpers.links.cancel")), panel_modells_path, :class => 'btn btn-default'

app/views/panel/modells/destroy.js.erb
$('#category_<%= @category.id %>').fadeOut();

app/views/panel/modells/edit.html.haml
- model_class = Modell

.row
  .col-sm-12
    .panel.panel-default.card-view
      .panel-heading
        .pull-left
          %h6.panel-title.txt-dark optional
        .clearfix
      .panel-wrapper.collapse.in
        .panel-body
          .form-wrap
            = render :partial => 'form'

app/views/panel/modells/index.html.haml
- model_class = Modell
- title 'Listing Models'
- header t '.title', :default => model_class.model_name.human.pluralize.titleize
- headercolor 'yellow'
- breadcrumb :brands

.row
  .col-sm-12
    .panel.panel-default.card-view
      .panel-heading
        .pull-left
          %h6.panel-title.txt-dark optional
        .clearfix
      .panel-wrapper.collapse.in
        .panel-body
          .form-wrap
            .table-responsive
              %table.table.table-striped
                %thead
                  %tr
                    %th= model_class.human_attribute_name(:id)
                    %th=t 'models.modell.fields.name'
                    %th=t 'models.modell.fields.year'
                    %th=t 'models.modell.fields.factorypics'
                    %th=t 'models.modell.fields.enabled'
                    %th=t 'models.modell.fields.brand_id'
                    %th= model_class.human_attribute_name(:created_at)
                    %th=t '.actions', :default => t("helpers.actions")
                %tbody
                  - @modells.each do |modell|
                    %tr
                      %td= link_to modell.id, panel_modell_path(modell)
                      %td= modell.name
                      %td= modell.year
                      %td
                        - modell.factorypics.each do |image|
                          = image_tag(image.url,height: '39')
                          %br
                      %td= modell.enabled
                      %td= modell.brand_id
                      %td=time_ago_in_words l modell.created_at
                      %td
                        = link_to t('.edit', :default => t("helpers.links.edit")), edit_panel_modell_path(modell), :class => 'btn btn-default btn-xs'
                        = link_to t('.destroy', :default => t("helpers.links.destroy")), panel_modell_path(modell), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

              = link_to t('.new', :default => t("helpers.links.new")), new_panel_modell_path, :class => 'btn btn-primary'

app/views/panel/modells/new.html.haml
- model_class = Modell

.row
  .col-sm-12
    .panel.panel-default.card-view
      .panel-heading
        .pull-left
          %h6.panel-title.txt-dark optional
        .clearfix
      .panel-wrapper.collapse.in
        .panel-body
          .form-wrap
            = render :partial => 'form'

app/views/panel/modells/show.html.haml
- model_class = Modell

/ Row
.row
  .col-sm-12
    .panel.panel-default.card-view
      .panel-wrapper.collapse.in
        .panel-body
          .row
            .col-md-5
              .item-big
                .col-lg-12
                  .panel.panel-default.card-view
                    .panel-heading
                      .pull-left
                        %h6.panel-title.txt-dark owl-carousel full width
                      .clearfix
                    .panel-wrapper.collapse.in
                      .panel-body
                        %div
                          #owl_demo_1.owl-carousel.owl-theme
                            -@modell.factorypics.each do |image|
                              .item
                                = image_tag(image.url ,width: '1000')
            .col-md-7
              .product-detail-wrap
                .product-rating.inline-block.mb-10
                  %a.fa.fa-star{:href => "javascript:void(0);"}
                  %a.fa.fa-star{:href => "javascript:void(0);"}
                  %a.fa.fa-star{:href => "javascript:void(0);"}
                  %a.fa.fa-star{:href => "javascript:void(0);"}
                  %a.fa.fa-star-o{:href => "javascript:void(0);"}
                .average-review.inline-block.mb-10
                   (
                  %span.review-count 5
                  customer review)
                %h3 #{@modell.name}

                %h4.mb-20 #{@modell.brand.name}
                =@modell.year.year if @modell.year?

                .product-price.head-font.mb-30 $ 1234
                %p.mb-50 Lorem ipsum dolor sit amet, facer velit at per, possit accusamus vim an. Cu vel possit dolorum. Elit placerat molestiae mea ne.Ex has movet ornatus, ei usu latine scripta molestiae. Sea ex aeterno adversarium, te ferri errem noluisse quo, meis civibus ea est. Sit in quas nostrud.

/ Row
/ Row
.row
  .col-sm-12
    .panel.panel-default.card-view
      .panel-wrapper.collapse.in
        .panel-body
          #example-tabs.product-detail-description
            %h3 Description
            %section
              %p Activist, criteria planned giving dignity, committed democratizing the global financial system progressive. Nelson Mandela equal opportunity change accelerate pathway to a better life invest our ambitions catalyst. Making progress contribution compassion Ford Foundation, cross-agency coordination Bill and Melinda Gates development. Overcome injustice tackling activism, promising development equality hack meaningful working families. Foundation; open source; organization volunteer, replicable think tank carbon emissions reductions.
            %h3 Aditional information
            %section
              .table-wrap
                .table-responsive
                  %table.table.mb-0
                    %tbody
                      %tr
                        %td SIZE
                        %td 31, 32, 33, 34, 35
                      %tr
                        %td COLOR
                        %td blue, red, rosa, white
                      %tr
                        %td TAGS
                        %td Diesel, shoe, stars
            %h3
              Review(
              %span.review-count> 0
              )
            %section
              %p.muted.review-tag No reviews yet.
              .row.mt-40
                .col-sm-6
                  .form-wrap
                    %form
                      .form-group
                        %label.control-label.mb-10{:for => "review"} Your rating
                        #star1.product-rating.starrr
                      .form-group
                        %label.control-label.mb-10{:for => "review"} Your review
                        %textarea#review.form-control{:placeholder => "add review"}
                      .row
                        .col-sm-6
                          .form-group
                            %label.control-label.mb-10{:for => "exampleInputuname_2"} User Name
                            %input#exampleInputuname_2.form-control{:placeholder => "Username", :type => "text"}/
                        .col-sm-6
                          .form-group
                            %label.control-label.mb-10{:for => "exampleInputEmail_2"} Email address
                            %input#exampleInputEmail_2.form-control{:placeholder => "Enter email", :type => "email"}/
                      .form-group.mb-0
                        %button.btn.btn-success.mr-10{:type => "submit"} Submit
                        / /Row


%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @modell.name
%p
  %strong= model_class.human_attribute_name(:year) + ':'
  %br
  = @modell.year
%p
  %strong= model_class.human_attribute_name(:enabled) + ':'
  %br
  = @modell.enabled
%p
  %strong= model_class.human_attribute_name(:brand_id) + ':'
  %br
  = @modell.brand_id
%p
  - @modell.categories.each do |cat|
    %br
    = cat.name

= link_to t('.back', :default => t("helpers.links.back")), panel_modells_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_panel_modell_path(@modell), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), panel_modell_path(@modell), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'