config/routes.rb
Rails.application.routes.draw do


  mount Payola::Engine => '/payola', as: :payola
  localized do
    #devise
    devise_for :users, :controllers => { :registrations => 'registrations' }
    devise_for :admin, :controllers => { :registrations => 'adminregistrations' }
    root 'shop/catalogs#index'

    #shop
    namespace :shop do
      root 'catalogs#index'

      get 'contact',to: 'static#contact'
      get 'testimonials',to: 'static#testimonials',as: 'testimonials'
      get 'about_us',to: 'static#aboutus',as: 'aboutus'

      resources :catalogs, only: [:index,:show]
      resources :categories, only: [:index,:show]
      resources :products, only: [:index,:show]
      resources :offers, only: [:index,:show]
      resources :brands, only: [:index,:show]

    end

    #panel
    namespace :panel do
      root 'static#home'
      get 'sell',to: 'static#sell',as: 'sell'
      get 'buy',to: 'static#buy',as: 'buy'

      resources :profiles, only: [:index,:show]
      resources :orders, only: [:index,:show]
      resources :invoices, only: [:index,:show]
      resources :carts, only: [:index,:show]

      resources :brands
      resources :modells, :path => 'models'
      resources :offers

    end

    #admin
    namespace :admin do
      root 'static#home'

      resources :categorymodels
      resources :modells, :path => 'models'
      resources :activities
      resources :profiles
      resources :brands
      resources :apps, :path => 'app'
      resources :categories
      resources :offers
      resources :incoterms
      resources :conditions


    end

  end


  #TO REVIEW or delete...
  scope '(:locale)', locale: /en|fr|es|de/ do

    resources :users, only: [:index]

    resources :conversations, only: [:index, :show, :destroy] do
      member do
        post :reply
        post :restore
        post :mark_as_read
      end
      collection do
        delete :empty_trash
      end
    end
    resources :messages, only: [:new, :create]

    #get 'shop/index'
    #get 'shop/category/:id', to: 'shop#category', as: 'shop_category'


  end

  namespace :api ,constraints: { format: 'json' } do
    namespace :v1 do
      resources :categories
    end
  end
end


# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/controllers/admin/conversations_controller.rb
class ConversationsController < AdminController
=begin
  before_action :authenticate_user!
  before_action :get_mailbox
  before_action :get_conversation, except: [:index, :empty_trash]
  before_action :get_box, only: [:index]

  def index
    @profile = current_user.profile
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end

    @conversations = @conversations.paginate(page: params[:page], per_page: 10)
  end


  def show
  end

  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end
  def mark_as_read
    @conversation.mark_as_read(current_user)
    flash[:success] = 'The conversation was marked as read.'
    redirect_to conversations_path
  end
  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end

  private

  def get_box
    if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
      params[:box] = 'inbox'
    end
    @box = params[:box]
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
    #TODO paginate
  end

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end
=end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/views/admin/conversations/_conversation.html.haml
%tr{:class => ('unread' unless conversation.is_unread?(current_user))}
  %td.inbox-small-cells
    %i.fa.fa-star
  %td.view-message.dont-show=link_to "#{conversation.subject}",conversation_path(conversation)
  %td.view-message=link_to "#{conversation.last_message.body}",conversation_path(conversation)
  %td.view-message.inbox-small-cells
    %i.fa.fa-paperclip
    - if conversation.is_trashed?(current_user)
      = link_to 'Restore', restore_conversation_path(conversation), class: 'fa.fa-paperclip', method: :post
    - else
      = link_to 'Move to trash', conversation_path(conversation), class: 'fa.fa-paperclip', method: :delete,
        data: {confirm: 'Are you sure?'}
      - if conversation.is_unread?(current_user)
        = link_to 'Mark as read', mark_as_read_conversation_path(conversation), class: 'fa.fa-paperclip', method: :post
  %td.view-message= render 'conversations/participants', conversation: conversation
  %td.view-message.text-right= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S")

app/views/admin/conversations/_form.html.haml
= simple_form_for :conversation, url: :conversations do |f|
  = f.input :recipients
  = f.input :subject
  = f.input :body, as: :text
  .form-actions
    = f.button :submit, class: 'btn-primary'
    = f.button :submit, 'Cancel', type: :reset, class: 'btn-danger'

app/views/admin/conversations/_participants.html.haml
-conversation.participants.each do |participant|
  - unless participant == current_user
    =link_to profile_path(participant.profile) do
      = gravatar_for participant

app/views/admin/conversations/index.html.haml
.row
  .col-lg-12
    .panel.panel-default.card-view
      .panel-wrapper.collapse.in
        .panel-body
          .mail-box
            .row
              %aside.col-md-3
                .user-head.text-center
                  %a.inbox-avatar.block{:href => "javascript:;"}
                    =gravatar_for(current_user,70)
                  .user-name
                    %h5
                      =link_to "#{profile.firstname}", profile_path(profile)
                    %span
                      %a=current_user.email
                .clearfix
                .mb-40
                  %a.btn.btn-success.btn-block.mt-30{:href => "#{new_message_url}", :title => "Compose"}
                    Compose
                %ul.inbox-nav.mb-30

                  = mailbox_section 'inbox', @box
                  = mailbox_section 'sent', @box
                  = mailbox_section 'trash', @box do
                    %a{:href => "#"}
                      %i.fa.fa-inbox
                      Inbox
                      %span.label.label-danger.pull-right 2
                  %li
                    %a{:href => "#"}
                      %i.fa.fa-envelope-o
                      Sent Messages
                  %li
                    %a{:href => "#"}
                      %i.fa.fa-trash-o
                      Trash

              %aside.col-md-9
                .inbox-head.mb-30
                  .row
                    %h3.col-sm-3 Inbox
                    .col-sm-offset-4.col-sm-5
                      %form{:role => "search"}
                        .input-group.mb-15
                          %input#example-input1-group21.form-control{:name => "example-input1-group21", :placeholder => "Search", :type => "text"}/
                          %span.input-group-btn
                            %button.btn.btn-success{:type => "button"}
                              %i.fa.fa-search
                .inbox-body
                  .table-responsive
                    - if @box == 'trash'
                      %p= link_to 'Empty trash', empty_trash_conversations_path, class: 'btn btn-danger', method: :delete,data: {confirm: 'Are you sure?'}
                    %table.table.table-inbox.table-hover
                      %tbody

                        = render partial: 'conversations/conversation', collection: @conversations
                      =will_paginate

app/views/admin/conversations/new.html.haml
.row
  .col-sm-12
    .panel.panel-default.card-view
      .panel-heading
        .pull-left
          %h6.panel-title.txt-dark New Conversation
        .clearfix
      .panel-wrapper.collapse.in
        .panel-body
          .form-wrap
            = render :partial => 'form'

app/views/admin/conversations/show.html.haml
.row
  .col-lg-12
    .panel.panel-default.card-view
      .panel-wrapper.collapse.in
        .panel-body
          .mail-box
            .row
              %aside.col-md-3
                .user-head.text-center
                  %a.inbox-avatar.block{:href => "javascript:;"}
                    =gravatar_for(current_user,70)
                  .user-name
                    %h5
                      =link_to "#{profile.firstname}", profile_path(profile)
                    %span
                      %a=current_user.email
                .clearfix
                .mb-40
                  %a.btn.btn-success.btn-block.mt-30{:href => "#{new_message_url}", :title => "Compose"}
                    Compose
                %ul.inbox-nav.mb-30

                  = mailbox_section 'inbox', @box
                  = mailbox_section 'sent', @box
                  = mailbox_section 'trash', @box do
                    %a{:href => "#"}
                      %i.fa.fa-inbox
                      Inbox
                      %span.label.label-danger.pull-right 2
                  %li
                    %a{:href => "#"}
                      %i.fa.fa-envelope-o
                      Sent Messages
                  %li
                    %a{:href => "#"}
                      %i.fa.fa-trash-o
                      Trash

              %aside.col-md-9
                .inbox-head.mb-30
                  .row
                    %h3.col-sm-4 Chatting with: #{render 'conversations/participants', conversation: @conversation}
                    .col-sm-offset-4.col-sm-4
                      %form{:role => "search"}
                        .input-group.mb-15
                          %input#example-input1-group21.form-control{:name => "example-input1-group21", :placeholder => "Search", :type => "text"}/
                          %span.input-group-btn
                            %button.btn.btn-success{:type => "button"}
                              %i.fa.fa-search
                .inbox-body
                  .heading-inbox
                    .row
                      .col-md-8
                        .compose-btn
                          %button.btn.btn-sm.mr-10{:title => "", :type => "button"}
                            %i.fa.fa-print
                          %button.btn.btn-sm{:title => ""}
                            %i.fa.fa-trash-o
                      .col-md-4.text-right
                        %span.date= time_ago_in_words(@conversation.last_message.created_at)
                    %hr.mt-25.mb-15/
                    .row
                      .col-md-12.mb-30
                        %h5= @conversation.subject
                  - @conversation.receipts_for(current_user).order(:created_at).each do |receipt|
                    - message = receipt.message
                    .sender-info
                      .row
                        .col-xs-12
                          .sender-img-wrap.pull-left.mr-20
                            = gravatar_for message.sender, 45, message.sender.name
                          .sender-details.pull-left
                            %span.capitalize-font.pr-5.txt-dark.block.font-15.head-font
                              %strong="#{message.sender.profile.firstname} says #{time_ago_in_words(message.created_at)} ago"
                            %span.block= message.body
                  = form_tag reply_conversation_path(@conversation), method: :post do
                    .form-group
                      -#= text_area_tag 'body', nil, id: :summernote, class: 'summernote'
                      = text_area_tag 'body', nil,  class: 'form-control ', placeholder: 'Type something...', required: true
                    = submit_tag "Send Message", class: 'btn btn-primary'