config/routes.rb
Rails.application.routes.draw do


  mount Payola::Engine => '/payola', as: :payola
  localized do
    #devise
    devise_for :users, :controllers => { :registrations => 'registrations' }
    devise_for :admin, :controllers => { :registrations => 'adminregistrations' }
    root 'shop/catalogs#index'

    #shop
    namespace :shop do
      root 'catalogs#index'

      get 'contact',to: 'static#contact'
      get 'testimonials',to: 'static#testimonials',as: 'testimonials'
      get 'about_us',to: 'static#aboutus',as: 'aboutus'

      resources :catalogs, only: [:index,:show]
      resources :categories, only: [:index,:show]
      resources :products, only: [:index,:show]
      resources :offers, only: [:index,:show]
      resources :brands, only: [:index,:show]

    end

    #panel
    namespace :panel do
      root 'static#home'
      get 'sell',to: 'static#sell',as: 'sell'
      get 'buy',to: 'static#buy',as: 'buy'

      resources :profiles, only: [:index,:show]
      resources :orders, only: [:index,:show]
      resources :invoices, only: [:index,:show]
      resources :carts, only: [:index,:show]

      resources :brands
      resources :modells, :path => 'models'
      resources :offers

    end

    #admin
    namespace :admin do
      root 'static#home'

      resources :categorymodels
      resources :modells, :path => 'models'
      resources :activities
      resources :profiles
      resources :brands
      resources :apps, :path => 'app'
      resources :categories
      resources :offers
      resources :incoterms
      resources :conditions


    end

  end


  #TO REVIEW or delete...
  scope '(:locale)', locale: /en|fr|es|de/ do

    resources :users, only: [:index]

    resources :conversations, only: [:index, :show, :destroy] do
      member do
        post :reply
        post :restore
        post :mark_as_read
      end
      collection do
        delete :empty_trash
      end
    end
    resources :messages, only: [:new, :create]

    #get 'shop/index'
    #get 'shop/category/:id', to: 'shop#category', as: 'shop_category'


  end

  namespace :api ,constraints: { format: 'json' } do
    namespace :v1 do
      resources :categories
    end
  end
end


# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/profile.rb
class Profile < ApplicationRecord
  include PublicActivity::Model
  extend FriendlyId

  tracked owner:  -> (controller, model ) {controller && controller.current_user}
  mount_uploader :picture, AvatarUploader
  friendly_id :slug_candidates, use: [:slugged, :finders]
  acts_as_paranoid
  #searchkick

  belongs_to :user
  belongs_to :admin

  def slug_candidates
    [
        :firstname,
        [:firstname, :lastname]
    ]
  end
  def should_generate_new_friendly_id?
    firstname_changed? || super
  end
end

app/controllers/admin/profiles_controller.rb
class Admin::ProfilesController < AdminController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to admin_profile_path(@profile), notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to admin_profile_path(@profile), notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to admin_profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_profile
    @profile = Profile.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def profile_params
    params.require(:profile).permit(:firstname, :lastname, :location, :status, :picture)
  end
end

app/controllers/panel/brands_controller.rb
class Panel::BrandsController < PanelController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    if params[:tag]
      @brands = Brand.tagged_with(params[:tag])
    else
      @brands = Brand.all
    end
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        #track_activity @brand
        format.html { redirect_to panel_brand_path(@brand), notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        #track_activity @brand
        format.html { redirect_to panel_brand_path(@brand), notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    #track_activity @brand
    respond_to do |format|
      format.html { redirect_to panel_brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_brand
    @brand = Brand.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def brand_params
    params.require(:brand).permit(:name, :sdescription, :description,:tag_list, :logo, :metatitle, :enable)
  end
end

app/controllers/panel/carts_controller.rb
class Panel::CartsController < PanelController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]
  #skip_before_action :authenticate_user!, only: [:index,:show],raise: false


  # GET /brands/1
  # GET /brands/1.json
  def show
    #@products=@brand.modells
  end
  def index

  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      #@brand = Brand.friendly.find(params[:id])
    end

end

app/controllers/panel/invoices_controller.rb
class Panel::InvoicesController < PanelController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]
  #skip_before_action :authenticate_user!, only: [:index,:show],raise: false


  # GET /brands/1
  # GET /brands/1.json
  def show
    #@products=@brand.modells
  end
  def index
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      #@brand = Brand.friendly.find(params[:id])
    end

end

app/controllers/panel/modells_controller.rb
class Panel::ModellsController < PanelController
  before_action :set_modell, only: [:show, :edit, :update, :destroy]

  # GET /modells
  # GET /modells.json
  def index
    if params[:tag]
      @modells = Modell.tagged_with(params[:tag])
    else
      @modells = Modell.all
    end
  end

  # GET /modells/1
  # GET /modells/1.json
  def show
  end

  # GET /modells/new
  def new
    @chosen_category = Category.find_by(id: params[:to].to_i) if params[:to]
    @modell = Modell.new
  end

  # GET /modells/1/edit
  def edit
  end

  def tag_cloud
    @tags = Modell.tag_counts_on(:tags)
  end

  # POST /modells
  # POST /modells.json
  def create
    @modell = Modell.new(modell_params)

    respond_to do |format|
      if @modell.save
        @categories = Category.where(id: params['categories'])
        @categories.each do |cat|
          @modell.categorymodels.create(show: cat)
        end
        format.html { redirect_to panel_modell_path(@modell), notice: 'Modell was successfully created.' }
        format.json { render :show, status: :created, location: @modell }
      else
        format.html { render :new }
        format.json { render json: @modell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /modells/1
  # PATCH/PUT /modells/1.json
  def update
    respond_to do |format|
      #TODO Improve method
      @modell.categorymodels.delete_all
      @categories = Category.where(id: params['categories'])
      @categories.each do |cat|
        @modell.categorymodels.create(show: cat)
      end
      #@modell.categorymodels.create(@categories)
      if @modell.update(modell_params)
        format.html { redirect_to panel_modell_path(@modell), notice: 'Modell was successfully updated.' }
        format.json { render :show, status: :ok, location: @modell }
      else
        format.html { render :edit }
        format.json { render json: @modell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /modells/1
  # DELETE /modells/1.json
  def destroy
    @modell.destroy
    respond_to do |format|
      format.html { redirect_to panel_modells_url, notice: 'Modell was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_modell
    @modell = Modell.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def modell_params
    params.require(:modell).permit(:name, :year, {factorypics: []},:tag_list,:enabled, :brand_id,:country_code)
  end
end

app/controllers/panel/offers_controller.rb
class Panel::OffersController < PanelController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    if params[:tag]
      @offers = Offer.tagged_with(params[:tag])
    else
      @offers = Offer.all
    end
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to panel_offer_path(@offer), notice: 'Offer was successfully created.' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to panel_offer_path(@offer), notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to panel_offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_offer
    @offer = Offer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def offer_params
    params.require(:offer).permit(:serialnumber, :machinenumber,:tag_list, :agedate, :condition_id, :incoterm_id, {images: []}, :description, :avability, :price_cents, :modell_id, :enabled)
  end
end

app/controllers/panel/orders_controller.rb
class Panel::OrdersController < PanelController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  #skip_before_action :authenticate_user!, only: [:index,:show],raise: false


  # GET /brands/1
  # GET /brands/1.json
  def show
    #@products=@brand.modells
  end
  def index

  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      #@brand = Brand.friendly.find(params[:id])
    end

end

app/controllers/panel/profiles_controller.rb
class Panel::ProfilesController < PanelController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to panel_profile_path(@profile), notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to panel_profile_path(@profile), notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to panel_profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:firstname, :lastname, :location, :status, :picture)
    end
end

app/controllers/panel/static_controller.rb
class  Panel::StaticController < PanelController
 #skip_before_action :authenticate_user!
  def home

  end

  def contact
  end
  def testimonials

  end
  def aboutus

  end
  def buy

  end
  def sell

  end
end

app/controllers/panel_controller.rb
class PanelController < ApplicationController
  before_action :authenticate_user!
  #protect_from_forgery with: :exception
end

app/views/panel/profiles/_form.html.haml
= simple_form_for [:admin, @profile], :html => { :class => 'form-horizontal' } do |f|
  = f.input :firstname
  = f.error_span :firstname
  = f.input :lastname
  = f.error_span :lastname
  = f.input :location
  = f.error_span :location
  = f.input :status
  = f.error_span :status
  = f.input :picture
  = f.error_span :picture
  = f.input :user_id
  = f.error_span :user_id


  = f.input :deleted_at
  = f.error_span :deleted_at
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), admin_profiles_path, :class => 'btn btn-default'

app/views/panel/profiles/edit.html.haml
- model_class = Profile

- title t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
- header t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
- headercolor 'green'
- breadcrumb @profile

.row
  .col-sm-12
    .panel.panel-default.card-view
      .panel-heading
        .pull-left
          %h6.panel-title.txt-dark=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
        .clearfix
      .panel-wrapper.collapse.in
        .panel-body
          .form-wrap
            = render :partial => 'form'

app/views/panel/profiles/index.html.haml
- model_class = Profile

- title t '.title', :default => model_class.model_name.human.pluralize.titleize
- header t '.title', :default => model_class.model_name.human.pluralize.titleize
- headercolor 'green'
- breadcrumb :profiles

.row
  .col-sm-12
    .panel.panel-default.card-view
      .panel-heading
        .pull-left
          %h6.panel-title.txt-dark=model_class.model_name.human.pluralize.titleize
        .clearfix
      .panel-wrapper.collapse.in
        .panel-body
          .form-wrap
            .table-responsive
              %table.table.table-striped
                %thead
                  %tr
                    %th= model_class.human_attribute_name(:id)
                    %th= model_class.human_attribute_name(:firstname)
                    %th= model_class.human_attribute_name(:lastname)
                    %th= model_class.human_attribute_name(:location)
                    %th= model_class.human_attribute_name(:status)
                    %th= model_class.human_attribute_name(:picture)
                    %th= model_class.human_attribute_name(:user_id)
                    %th= model_class.human_attribute_name(:deleted_at)
                    %th= model_class.human_attribute_name(:created_at)
                    %th=t '.actions', :default => t("helpers.actions")
                %tbody
                  - @profiles.each do |profile|
                    %tr
                      %td= link_to profile.id, admin_profile_path(profile)
                      %td= profile.firstname
                      %td= profile.lastname
                      %td= profile.location
                      %td= profile.status
                      %td= image_tag(profile.picture, height: '50')
                      %td= profile.user_id
                      %td= profile.deleted_at
                      %td=l profile.created_at
                      %td
                        = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_profile_path(profile), :class => 'btn btn-default btn-xs'
                        = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_profile_path(profile), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

              = link_to t('.new', :default => t("helpers.links.new")), new_admin_profile_path, :class => 'btn btn-primary'

app/views/panel/profiles/new.html.haml
- model_class = Profile

- title t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
- header t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
- headercolor 'green'
- breadcrumb @profile

.row
  .col-sm-12
    .panel.panel-default.card-view
      .panel-heading
        .pull-left
          %h6.panel-title.txt-dark=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
        .clearfix
      .panel-wrapper.collapse.in
        .panel-body
          .form-wrap
            = render :partial => 'form'

app/views/panel/profiles/show.html.haml
- model_class = Profile

- title t '.title', :default => [:'helpers.titles.show', 'Show %{model}'], :model => model_class.model_name.human.titleize
- header t '.title', :default => [:'helpers.titles.show', 'Show %{model}'], :model => model_class.model_name.human.titleize
- headercolor 'green'
- breadcrumb @profile
- languages_panel @profile

.main-content.container-fluid
  .user-profile
    .row
      .col-md-5
        .user-display
          .user-display-bg
            =image_tag 'profilebg.png'
          .user-display-bottom
            .user-display-avatar
              =gravatar_for(current_user,90)
            .user-display-info
              .name="#{@profile.firstname} #{@profile.lastname}"
              .nick
                %span.mdi.mdi-account
                =@profile.admin.email if !@profile.admin.nil?
                =@profile.user.email if !@profile.user.nil?

            .row.user-display-details
              .col-xs-4
                .title Followers
                .counter 26
              .col-xs-4
                .title Following
                .counter 26
              .col-xs-4
                .title Member from
                .counter
                  =t time_ago_in_words(@profile.created_at)
        .user-info-list.panel.panel-default
          .panel-heading.panel-heading-divider
            About Me
            %span.panel-subtitle I am a web developer and designer based in Montreal - Canada, I like read books, good music and nature.
          .panel-body
            %table.no-border.no-strip.skills
              %tbody.no-border-x.no-border-y
                %tr
                  %td.icon
                    %span.mdi.mdi-case
                  %td.item
                    Ocupation
                    %span.icon.s7-portfolio
                  %td Developer and designer
                %tr
                  %td.icon
                    %span.mdi.mdi-cake
                  %td.item
                    Birthday
                    %span.icon.s7-gift
                  %td 16 September 1989
                %tr
                  %td.icon
                    %span.mdi.mdi-smartphone-android
                  %td.item
                    Mobile
                    %span.icon.s7-phone
                  %td (999) 999-9999
                %tr
                  %td.icon
                    %span.mdi.mdi-globe-alt
                  %td.item
                    Location
                    %span.icon.s7-map-marker
                  %td Montreal, Canada
                %tr
                  %td.icon
                    %span.mdi.mdi-pin
                  %td.item
                    Website
                    %span.icon.s7-global
                  %td www.website.com

      .col-md-6
        .panel.panel-default
          .panel-heading.panel-heading-divider
            Latest Activity
            %span.panel-subtitle This is a custom timeline widget
          .panel-body
            %ul.user-timeline
              %li.latest
                .user-timeline-date Just Now
                .user-timeline-title Create New Page
                .user-timeline-description Quisque sed est felis. Vestibulum lectus nulla, maximus in eros non, tristique consectetur lorem. Nulla molestie sem quis imperdiet facilisis
              %li
                .user-timeline-date Today - 15:35
                .user-timeline-title Back Up Theme
                .user-timeline-description Quisque sed est felis. Vestibulum lectus nulla, maximus in eros non, tristique consectetur lorem. Nulla molestie sem quis imperdiet facilisis
              %li
                .user-timeline-date Yesterday - 10:41
                .user-timeline-title Changes In The Structure
                .user-timeline-description Quisque sed est felis. Vestibulum lectus nulla, maximus in eros non, tristique consectetur lorem. Nulla molestie sem quis imperdiet facilisis