config/routes.rb
Rails.application.routes.draw do


  mount Payola::Engine => '/payola', as: :payola
  localized do
    #devise
    devise_for :users, :controllers => { :registrations => 'registrations' }
    devise_for :admin, :controllers => { :registrations => 'adminregistrations' }
    root 'shop/catalogs#index'

    #shop
    namespace :shop do
      root 'catalogs#index'

      get 'contact',to: 'static#contact'
      get 'testimonials',to: 'static#testimonials',as: 'testimonials'
      get 'about_us',to: 'static#aboutus',as: 'aboutus'

      resources :catalogs, only: [:index,:show]
      resources :categories, only: [:index,:show]
      resources :products, only: [:index,:show]
      resources :offers, only: [:index,:show]
      resources :brands, only: [:index,:show]

    end

    #panel
    namespace :panel do
      root 'static#home'
      get 'sell',to: 'static#sell',as: 'sell'
      get 'buy',to: 'static#buy',as: 'buy'

      resources :profiles, only: [:index,:show]
      resources :orders, only: [:index,:show]
      resources :invoices, only: [:index,:show]
      resources :carts, only: [:index,:show]

      resources :brands
      resources :modells, :path => 'models'
      resources :offers

    end

    #admin
    namespace :admin do
      root 'static#home'

      resources :categorymodels
      resources :modells, :path => 'models'
      resources :activities
      resources :profiles
      resources :brands
      resources :apps, :path => 'app'
      resources :categories
      resources :offers
      resources :incoterms
      resources :conditions


    end

  end


  #TO REVIEW or delete...
  scope '(:locale)', locale: /en|fr|es|de/ do

    resources :users, only: [:index]

    resources :conversations, only: [:index, :show, :destroy] do
      member do
        post :reply
        post :restore
        post :mark_as_read
      end
      collection do
        delete :empty_trash
      end
    end
    resources :messages, only: [:new, :create]

    #get 'shop/index'
    #get 'shop/category/:id', to: 'shop#category', as: 'shop_category'


  end

  namespace :api ,constraints: { format: 'json' } do
    namespace :v1 do
      resources :categories
    end
  end
end


# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/incoterm.rb
class Incoterm < ApplicationRecord
  include PublicActivity::Model
  extend FriendlyId

  tracked owner:  -> (controller, model ) {controller && controller.current_user}
  mount_uploader :picture, AvatarUploader
  friendly_id :slug_candidates, use: [:slugged, :finders]
  acts_as_paranoid

  def slug_candidates
    [
        :smalltag,
        [:smalltag, :name]
    ]
  end
  def should_generate_new_friendly_id?
    smalltag_changed? || super
  end
end

app/controllers/admin/incoterms_controller.rb
class Admin::IncotermsController < AdminController
  before_action :set_incoterm, only: [:show, :edit, :update, :destroy]

  # GET /incoterms
  # GET /incoterms.json
  def index
    @incoterms = Incoterm.all
  end

  # GET /incoterms/1
  # GET /incoterms/1.json
  def show
  end

  # GET /incoterms/new
  def new
    @incoterm = Incoterm.new
  end

  # GET /incoterms/1/edit
  def edit
  end

  # POST /incoterms
  # POST /incoterms.json
  def create
    @incoterm = Incoterm.new(incoterm_params)

    respond_to do |format|
      if @incoterm.save
        format.html { redirect_to admin_incoterm_path(@incoterm), notice: 'Incoterm was successfully created.' }
        format.json { render :show, status: :created, location: @incoterm }
      else
        format.html { render :new }
        format.json { render json: @incoterm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incoterms/1
  # PATCH/PUT /incoterms/1.json
  def update
    respond_to do |format|
      if @incoterm.update(incoterm_params)
        format.html { redirect_to admin_incoterm_path(@incoterm), notice: 'Incoterm was successfully updated.' }
        format.json { render :show, status: :ok, location: @incoterm }
      else
        format.html { render :edit }
        format.json { render json: @incoterm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incoterms/1
  # DELETE /incoterms/1.json
  def destroy
    @incoterm.destroy
    respond_to do |format|
      format.html { redirect_to admin_incoterms_url, notice: 'Incoterm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_incoterm
    @incoterm = Incoterm.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def incoterm_params
    params.require(:incoterm).permit(:smalltag, :name, :description)
  end
end

app/views/admin/incoterms/_form.html.haml
.row

  = simple_form_for [:admin, @incoterm],remote: true, :html => { :class => 'form-group' } do |f|
    .col-sm-12
      = f.input :smalltag
      = f.error_span :smalltag
      = f.input :name
      = f.error_span :name
      = f.input :description
      = f.error_span :description
    .col-sm-6
      = f.button :submit, :class => 'btn-primary'
    .col-sm-6
      = link_to t('.cancel', :default => t("helpers.links.cancel")), admin_incoterms_path, :class => 'btn btn-default'

app/views/admin/incoterms/_incoterm.html.haml
%tr{:id => "incoterm_#{incoterm.id}"}
  %td= link_to incoterm.id, admin_incoterm_path(incoterm)
  %td= incoterm.smalltag
  %td= incoterm.name
  %td= incoterm.description
  %td=t time_ago_in_words(incoterm.created_at)
  %td
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_incoterm_path(incoterm),remote: true, :class => 'btn btn-default btn-xs'
    = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_incoterm_path(incoterm), :method => :delete, remote:true, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

app/views/admin/incoterms/create.js.erb
$('#dialog').modal('toggle');
$('#incoterms').append('<%= j render (@incoterm) %>')

app/views/admin/incoterms/destroy.js.erb
$('#incoterm_<%= @incoterm.id %>').fadeOut();

app/views/admin/incoterms/edit.js.erb
$('#dialog h3').html("<i class=' glyphicon glyphicon-pencil'></i> Edit Customer");
$('.modal-body').html('<%= j render("form") %>');
$('#dialog').modal("show");
$('#dialog').on('shown.bs.modal', function () {
  $('.first_input').focus()
})

app/views/admin/incoterms/index.html.haml
- model_class = Incoterm

- title t '.title', :default => model_class.model_name.human.pluralize.titleize
- header t '.title', :default => model_class.model_name.human.pluralize.titleize
- headercolor 'green'
- breadcrumb :incoterms
- languages_admin

.row
  .col-sm-12
    .panel.panel-default.card-view
      .panel-heading
        .pull-left
          %h6.panel-title.txt-dark=model_class.model_name.human.pluralize.titleize
        .clearfix
      .panel-wrapper.collapse.in
        .panel-body
          .form-wrap
            .table-responsive
              %table.table.table-striped
                %thead
                  %tr
                    %th= model_class.human_attribute_name(:id)
                    %th= model_class.human_attribute_name(:smalltag)
                    %th= model_class.human_attribute_name(:name)
                    %th= model_class.human_attribute_name(:description)
                    %th= model_class.human_attribute_name(:created_at)
                    %th=t '.actions', :default => t("helpers.actions")
                %tbody{id: 'incoterms'}
                  =render @incoterms

              = link_to t('.new', :default => t("helpers.links.new")), new_admin_incoterm_path, remote: true, :class => 'btn btn-primary'
= render 'layouts/dialog'

app/views/admin/incoterms/new.js.erb
// Add the dialog title
$('#dialog h3').html("<i class='glyphicon glyphicon-plus'></i> Add New Customer");

// Render the new form
$('.modal-body').html('<%= j render("form") %>');

// Show the dynamic dialog
$('#dialog').modal("show");

// Set focus to the first element
$('#dialog').on('shown.bs.modal', function () {
  $('.first_input').focus()
})

app/views/admin/incoterms/show.html.haml
- model_class = Incoterm

- title t '.title', :default => [:'helpers.titles.show', 'Show %{model}'], :model => model_class.model_name.human.titleize
- header t '.title', :default => [:'helpers.titles.show', 'Show %{model}'], :model => model_class.model_name.human.titleize
- headercolor 'green'
- breadcrumb @incoterm


.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:smalltag) + ':'
  %br
  = @incoterm.smalltag
%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @incoterm.name
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @incoterm.description



= link_to t('.back', :default => t("helpers.links.back")), admin_incoterms_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_incoterm_path(@incoterm), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), admin_incoterm_path(@incoterm), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/admin/incoterms/update.js.erb
$('#dialog').modal('toggle');
$('#incoterm_<%= @incoterm.id %>').replaceWith('<%= j render (@incoterm) %>')